CREATE TABLE [Info].[WROrders] (
    [OrderID]             INT          IDENTITY (1, 1) NOT NULL,
    [CustomerID]          VARCHAR (5)  NULL,
    [OrderDate]           DATETIME     NULL,
    [PurchaseOrderNumber] VARCHAR (30) NULL,
    [ShipName]            VARCHAR (50) NULL,
    [ShipAddress1]        VARCHAR (35) NULL,
    [ShipAddress2]        VARCHAR (32) NULL,
    [ShipCity]            VARCHAR (50) NULL,
    [ShipState]           VARCHAR (50) NULL,
    [ShipPostalCode]      VARCHAR (20) NULL,
    [SCreditCardNo]       VARCHAR (50) NULL,
    [SExpDate]            VARCHAR (50) NULL,
    [SChargeStatus]       VARCHAR (60) NULL,
    [Bookstore]           BIT          NOT NULL,
    [Foreign]             BIT          NOT NULL,
    [AmtPaid]             MONEY        NULL,
    [Message1]            VARCHAR (80) NULL,
    [Message2]            VARCHAR (80) NULL,
    [Message3]            VARCHAR (80) NULL,
    [Message4]            VARCHAR (80) NULL,
    CONSTRAINT [PK_WROrders] PRIMARY KEY CLUSTERED ([OrderID] ASC),
    CONSTRAINT [FK_WROrders_WRCustomerSubscriberMember] FOREIGN KEY ([CustomerID]) REFERENCES [Info].[WRCustomerSubscriberMember] ([CustomerId])
);

