CREATE TABLE [Beholder].[MediaCorrespondence] (
    [Id]                           INT            IDENTITY (1, 1) NOT NULL,
    [MediaTypeId]                  INT            NULL,
    [CorrespondenceTypeId]         INT            NULL,
    [CorrespondenceName]           VARCHAR (100)  NULL,
    [DateReceived]                 DATETIME2 (7)  NULL,
    [MovementClassId]              INT            NULL,
    [ConfidentialityTypeId]        INT            NULL,
    [ToName]                       VARCHAR (80)   NULL,
    [FromName]                     VARCHAR (80)   NULL,
    [DateRenewalPermission]        DATETIME2 (7)  NULL,
    [RenewalPermissionTypeId]      INT            NULL,
    [RenewalPermission]            VARCHAR (500)  NULL,
    [Summary]                      VARCHAR (4000) NULL,
    [City]                         VARCHAR (40)   NULL,
    [County]                       VARCHAR (40)   NULL,
    [StateId]                      INT            NULL,
    [DateCreated]                  DATETIME2 (7)  NULL,
    [CreatedUserId]                INT            NULL,
    [DateModified]                 DATETIME2 (7)  NULL,
    [ModifiedUserId]               INT            NULL,
    [RemovalStatusId]              INT            NULL,
    [RemovalReason]                VARCHAR (50)   NULL,
    [DateDeleted]                  DATETIME2 (7)  NULL,
    [DeletedUserId]                INT            NULL,
    [MediaCorrespondenceContextId] INT            NULL,
    [CatalogId]                    VARCHAR (10)   NULL,
    CONSTRAINT [PK_MediaCorrespondence] PRIMARY KEY CLUSTERED ([Id] ASC) ON [BeholderData1],
    CONSTRAINT [FK_MediaCorrespondence_ConfidentialityType] FOREIGN KEY ([ConfidentialityTypeId]) REFERENCES [Beholder].[ConfidentialityType] ([Id]),
    CONSTRAINT [FK_MediaCorrespondence_CreatedUser] FOREIGN KEY ([CreatedUserId]) REFERENCES [Security].[User] ([Id]),
    CONSTRAINT [FK_MediaCorrespondence_DeletedUser] FOREIGN KEY ([DeletedUserId]) REFERENCES [Security].[User] ([Id]),
    CONSTRAINT [FK_MediaCorrespondence_MediaType] FOREIGN KEY ([MediaTypeId]) REFERENCES [Beholder].[MediaType] ([Id]),
    CONSTRAINT [FK_MediaCorrespondence_ModifiedUser] FOREIGN KEY ([ModifiedUserId]) REFERENCES [Security].[User] ([Id]),
    CONSTRAINT [FK_MediaCorrespondence_MovementClass] FOREIGN KEY ([MovementClassId]) REFERENCES [Beholder].[MovementClass] ([Id]),
    CONSTRAINT [FK_MediaCorrespondence_RemovalStatus] FOREIGN KEY ([RemovalStatusId]) REFERENCES [Beholder].[RemovalStatus] ([Id]),
    CONSTRAINT [FK_MediaCorrespondence_RenewalPermmisionType] FOREIGN KEY ([RenewalPermissionTypeId]) REFERENCES [Beholder].[RenewalPermmisionType] ([Id]),
    CONSTRAINT [FK_MediaCorrespondence_State] FOREIGN KEY ([StateId]) REFERENCES [Common].[State] ([Id])
);

