CREATE TABLE [Beholder].[MediaWebsiteEGroup] (
    [Id]                          INT            IDENTITY (1, 1) NOT NULL,
    [MediaTypeId]                 INT            NOT NULL,
    [WebsiteEGroupTypeId]         INT            NULL,
    [Name]                        VARCHAR (100)  NULL,
    [URL]                         VARCHAR (255)  NULL,
    [DateDiscovered]              DATETIME2 (7)  NULL,
    [DatePublished]               DATETIME2 (7)  NULL,
    [DateOffline]                 DATETIME2 (7)  NULL,
    [IPAddress]                   VARCHAR (20)   NULL,
    [NewsSourceId]                INT            NULL,
    [MovementClassId]             INT            NULL,
    [ConfidentialityTypeId]       INT            NULL,
    [ActiveYear]                  INT            NULL,
    [ActiveStatusId]              INT            NULL,
    [IsReported]                  BIT            NULL,
    [ApprovalStatusId]            INT            NULL,
    [WhoIsInfo]                   VARCHAR (4000) NULL,
    [Summary]                     VARCHAR (4000) NULL,
    [City]                        VARCHAR (40)   NULL,
    [County]                      VARCHAR (40)   NULL,
    [StateId]                     INT            NULL,
    [DateCreated]                 DATETIME2 (7)  NOT NULL,
    [CreatedUserId]               INT            NOT NULL,
    [DateModified]                DATETIME2 (7)  NULL,
    [ModifiedUserId]              INT            NULL,
    [RemovalStatusId]             INT            NULL,
    [RemovalReason]               VARCHAR (50)   NULL,
    [DateDeleted]                 DATETIME2 (7)  NULL,
    [DeletedUserId]               INT            NULL,
    [MediaWebsiteEGroupContextId] INT            NULL,
    CONSTRAINT [PK_WebsiteEGroup] PRIMARY KEY CLUSTERED ([Id] ASC) ON [BeholderData1]
);

