CREATE TABLE [Beholder].[Vehicle] (
    [Id]              INT           IDENTITY (1, 1) NOT NULL,
    [VehicleMakeId]   INT           NULL,
    [VehicleModelId]  INT           NULL,
    [VehicleTypeId]   INT           NULL,
    [VehicleColorId]  INT           NULL,
    [VIN]             VARCHAR (20)  NULL,
    [VehicleYear]     INT           NULL,
    [DateCreated]     DATETIME2 (7) CONSTRAINT [DF_Vehicle_DateCreated] DEFAULT (getdate()) NOT NULL,
    [CreatedUserId]   INT           NOT NULL,
    [DateModified]    DATETIME2 (7) NULL,
    [ModifiedUserId]  INT           NULL,
    [RemovalStatusId] INT           NULL,
    [RemovalReason]   VARCHAR (50)  NULL,
    [DateDeleted]     DATETIME2 (7) NULL,
    [DeletedUserId]   INT           NULL,
    CONSTRAINT [PK_Vehicle] PRIMARY KEY CLUSTERED ([Id] ASC) ON [BeholderData1],
    CONSTRAINT [FK_Vehicle_CreatedUser] FOREIGN KEY ([CreatedUserId]) REFERENCES [Security].[User] ([Id]),
    CONSTRAINT [FK_Vehicle_DeletedUser] FOREIGN KEY ([DeletedUserId]) REFERENCES [Security].[User] ([Id]),
    CONSTRAINT [FK_Vehicle_ModifiedUser] FOREIGN KEY ([ModifiedUserId]) REFERENCES [Security].[User] ([Id]),
    CONSTRAINT [FK_Vehicle_RemovalStatus] FOREIGN KEY ([RemovalStatusId]) REFERENCES [Beholder].[RemovalStatus] ([Id]),
    CONSTRAINT [FK_Vehicle_VehicleColor] FOREIGN KEY ([VehicleColorId]) REFERENCES [Beholder].[VehicleColor] ([Id]),
    CONSTRAINT [FK_Vehicle_VehicleMake] FOREIGN KEY ([VehicleMakeId]) REFERENCES [Beholder].[VehicleMake] ([Id]),
    CONSTRAINT [FK_Vehicle_VehicleModel] FOREIGN KEY ([VehicleModelId]) REFERENCES [Beholder].[VehicleModel] ([Id]),
    CONSTRAINT [FK_Vehicle_VehicleType] FOREIGN KEY ([VehicleTypeId]) REFERENCES [Beholder].[VehicleType] ([Id])
);

