CREATE TABLE [Common].[Address] (
    [Id]                 INT               IDENTITY (1, 1) NOT NULL,
    [Address1]           VARCHAR (256)     NULL,
    [Address2]           VARCHAR (256)     NULL,
    [City]               VARCHAR (256)     NULL,
    [County]             VARCHAR (256)     NULL,
    [Country]            VARCHAR (256)     NULL,
    [StateId]            INT               NULL,
    [Zip5]               CHAR (5)          NULL,
    [Zip4]               CHAR (4)          NULL,
    [Longitude]          NUMERIC (9, 6)    NULL,
    [Latitude]           NUMERIC (9, 6)    NULL,
    [GeographicLocation] [sys].[geography] NULL,
    [DateCreated]        DATETIME2 (7)     CONSTRAINT [DF_Address_DateCreated] DEFAULT (getdate()) NOT NULL,
    [CreatedUserId]      INT               NOT NULL,
    [DateModified]       DATETIME2 (7)     NULL,
    [ModifiedUserId]     INT               NULL,
    [DateDeleted]        DATETIME2 (7)     NULL,
    [DeletedUserId]      INT               NULL,
    CONSTRAINT [PK_Address] PRIMARY KEY CLUSTERED ([Id] ASC) ON [CommonDATA1],
    CONSTRAINT [FK_Address_CreatedUser] FOREIGN KEY ([CreatedUserId]) REFERENCES [Security].[User] ([Id]),
    CONSTRAINT [FK_Address_DeletedUser] FOREIGN KEY ([DeletedUserId]) REFERENCES [Security].[User] ([Id]),
    CONSTRAINT [FK_Address_ModifiedUser] FOREIGN KEY ([ModifiedUserId]) REFERENCES [Security].[User] ([Id]),
    CONSTRAINT [FK_Address_State] FOREIGN KEY ([StateId]) REFERENCES [Common].[State] ([Id])
) TEXTIMAGE_ON [CommonDATA1];

