CREATE TABLE [Common].[Person] (
    [Id]                          INT           IDENTITY (1, 1) NOT NULL,
    [SSN]                         CHAR (9)      NULL,
    [PrefixId]                    INT           NULL,
    [FName]                       VARCHAR (256) NULL,
    [MName]                       VARCHAR (256) NULL,
    [LName]                       VARCHAR (256) NOT NULL,
    [SuffixId]                    INT           NULL,
    [DOB]                         DATETIME2 (7) NULL,
    [ActualDOBIndicator]          BIT           NULL,
    [GenderId]                    INT           NULL,
    [LicenseTypeId]               INT           NULL,
    [DriversLicenseNumber]        VARCHAR (125) NULL,
    [DriversLicenseStateId]       INT           NULL,
    [DeceasedDate]                DATETIME2 (7) NULL,
    [ActualDeceasedDateIndicator] BIT           NULL,
    [HairColorId]                 INT           NULL,
    [HairPatternId]               INT           NULL,
    [EyeColorId]                  INT           NULL,
    [Height]                      VARCHAR (20)  NULL,
    [Weight]                      VARCHAR (20)  NULL,
    [RaceId]                      INT           NULL,
    [MartialStatusId]             INT           NULL,
    [DateCreated]                 DATETIME2 (7) CONSTRAINT [DF_Person_DateCreated] DEFAULT (getdate()) NOT NULL,
    [CreatedUserId]               INT           NULL,
    [DateModified]                DATETIME2 (7) NULL,
    [ModifiedUserId]              INT           NULL,
    [DateDeleted]                 DATETIME2 (7) NULL,
    [DeletedUserId]               INT           NULL,
    [OldId]                       INT           NULL,
    [OldContactId]                INT           NULL,
    CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED ([Id] ASC) ON [CommonDATA1],
    CONSTRAINT [FK_Person_CreatedUser] FOREIGN KEY ([CreatedUserId]) REFERENCES [Security].[User] ([Id]),
    CONSTRAINT [FK_Person_DeletedUser] FOREIGN KEY ([DeletedUserId]) REFERENCES [Security].[User] ([Id]),
    CONSTRAINT [FK_Person_EyeColor] FOREIGN KEY ([EyeColorId]) REFERENCES [Common].[EyeColor] ([Id]),
    CONSTRAINT [FK_Person_Gender] FOREIGN KEY ([GenderId]) REFERENCES [Common].[Gender] ([Id]),
    CONSTRAINT [FK_Person_HairColor] FOREIGN KEY ([HairColorId]) REFERENCES [Common].[HairColor] ([Id]),
    CONSTRAINT [FK_Person_HairPattern] FOREIGN KEY ([HairPatternId]) REFERENCES [Common].[HairPattern] ([Id]),
    CONSTRAINT [FK_Person_LicenseType] FOREIGN KEY ([LicenseTypeId]) REFERENCES [Common].[LicenseType] ([Id]),
    CONSTRAINT [FK_Person_MaritialStatus] FOREIGN KEY ([MartialStatusId]) REFERENCES [Common].[MaritialStatus] ([Id]),
    CONSTRAINT [FK_Person_ModifiedUser] FOREIGN KEY ([ModifiedUserId]) REFERENCES [Security].[User] ([Id]),
    CONSTRAINT [FK_Person_Prefix] FOREIGN KEY ([PrefixId]) REFERENCES [Common].[Prefix] ([Id]),
    CONSTRAINT [FK_Person_Race] FOREIGN KEY ([RaceId]) REFERENCES [Common].[Race] ([Id]),
    CONSTRAINT [FK_Person_State] FOREIGN KEY ([DriversLicenseStateId]) REFERENCES [Common].[State] ([Id]),
    CONSTRAINT [FK_Person_Suffix] FOREIGN KEY ([SuffixId]) REFERENCES [Common].[Suffix] ([Id])
);

