//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 1/27/2013 7:27:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using splc.infrastructure.Repository;

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace splc.domain
{

    /// <summary>
    /// There are no comments for splc.domain.BeholderEvent, splc.domain in the schema.
    /// </summary>
    public partial class BeholderEvent : IKeyed<int>
    {

        private int _Id;

        private string _EventName;

        private System.Nullable<System.DateTime> _EventDate;

        private string _Religion;

        private string _Summary;

        private string _Comments;

        private System.DateTime _DateCreated;

        private System.Nullable<System.DateTime> _DateModified;

        private System.Nullable<System.DateTime> _DateDeleted;

        private BeholderEventDocumentationType _BeholderEventDocumentationType;

        private Iesi.Collections.ISet _BeholderAddressEventRels;

        private BeholderConfidentialityType _BeholderConfidentialityType;

        private BeholderMovementClass _BeholderMovementClass;

        private BeholderWebIncidentType _BeholderWebIncidentType;

        private SecurityUser _SecurityUser_CreatedUserId;

        private SecurityUser _SecurityUser_DeletedUserId;

        private SecurityUser _SecurityUser_ModifiedUserId;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public BeholderEvent()
        {
            this._BeholderAddressEventRels = new Iesi.Collections.HashedSet();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }

    
        /// <summary>
        /// There are no comments for EventName in the schema.
        /// </summary>
        public virtual string EventName
        {
            get
            {
                return this._EventName;
            }
            set
            {
                this._EventName = value;
            }
        }

    
        /// <summary>
        /// There are no comments for EventDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> EventDate
        {
            get
            {
                return this._EventDate;
            }
            set
            {
                this._EventDate = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Religion in the schema.
        /// </summary>
        public virtual string Religion
        {
            get
            {
                return this._Religion;
            }
            set
            {
                this._Religion = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Summary in the schema.
        /// </summary>
        public virtual string Summary
        {
            get
            {
                return this._Summary;
            }
            set
            {
                this._Summary = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Comments in the schema.
        /// </summary>
        public virtual string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                this._Comments = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateCreated in the schema.
        /// </summary>
        public virtual System.DateTime DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this._DateCreated = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateModified in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this._DateModified = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateDeleted in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateDeleted
        {
            get
            {
                return this._DateDeleted;
            }
            set
            {
                this._DateDeleted = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderEventDocumentationType in the schema.
        /// </summary>
        public virtual BeholderEventDocumentationType BeholderEventDocumentationType
        {
            get
            {
                return this._BeholderEventDocumentationType;
            }
            set
            {
                this._BeholderEventDocumentationType = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAddressEventRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAddressEventRels
        {
            get
            {
                return this._BeholderAddressEventRels;
            }
            set
            {
                this._BeholderAddressEventRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderConfidentialityType in the schema.
        /// </summary>
        public virtual BeholderConfidentialityType BeholderConfidentialityType
        {
            get
            {
                return this._BeholderConfidentialityType;
            }
            set
            {
                this._BeholderConfidentialityType = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderMovementClass in the schema.
        /// </summary>
        public virtual BeholderMovementClass BeholderMovementClass
        {
            get
            {
                return this._BeholderMovementClass;
            }
            set
            {
                this._BeholderMovementClass = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderWebIncidentType in the schema.
        /// </summary>
        public virtual BeholderWebIncidentType BeholderWebIncidentType
        {
            get
            {
                return this._BeholderWebIncidentType;
            }
            set
            {
                this._BeholderWebIncidentType = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_CreatedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_CreatedUserId
        {
            get
            {
                return this._SecurityUser_CreatedUserId;
            }
            set
            {
                this._SecurityUser_CreatedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_DeletedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_DeletedUserId
        {
            get
            {
                return this._SecurityUser_DeletedUserId;
            }
            set
            {
                this._SecurityUser_DeletedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_ModifiedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_ModifiedUserId
        {
            get
            {
                return this._SecurityUser_ModifiedUserId;
            }
            set
            {
                this._SecurityUser_ModifiedUserId = value;
            }
        }
    }

}
