//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 1/27/2013 7:27:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using splc.infrastructure.Repository;

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace splc.domain
{

    /// <summary>
    /// There are no comments for splc.domain.BeholderOrganization, splc.domain in the schema.
    /// </summary>
    public partial class BeholderOrganization : IKeyed<int>
    {

        private int _Id;

        private string _OrganizationName;

        private string _OrganizationDesc;

        private int _ActiveYear;

        private bool _ReportStatusFlag;

        private System.Nullable<System.DateTime> _FormedDate;

        private System.Nullable<System.DateTime> _DisbandDate;

        private System.DateTime _DateCreated;

        private System.Nullable<System.DateTime> _DateModified;

        private System.Nullable<System.DateTime> _DateDeleted;

        private string _Comments;

        private Iesi.Collections.ISet _BeholderOrganizationStatusHistories;

        private Iesi.Collections.ISet _BeholderChapters;

        private BeholderActiveStatus _BeholderActiveStatus;

        private BeholderApprovalStatus _BeholderApprovalStatus;

        private BeholderConfidentialityType _BeholderConfidentialityType;

        private BeholderMovementClass _BeholderMovementClass;

        private BeholderOrganizationType _BeholderOrganizationType;

        private SecurityUser _SecurityUser_CreatedUserId;

        private SecurityUser _SecurityUser_DeletedUserId;

        private SecurityUser _SecurityUser_ModifiedUserId;

        private Iesi.Collections.ISet _BeholderAliasOrganizationRels;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public BeholderOrganization()
        {
            this._BeholderOrganizationStatusHistories = new Iesi.Collections.HashedSet();
            this._BeholderChapters = new Iesi.Collections.HashedSet();
            this._BeholderAliasOrganizationRels = new Iesi.Collections.HashedSet();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }

    
        /// <summary>
        /// There are no comments for OrganizationName in the schema.
        /// </summary>
        public virtual string OrganizationName
        {
            get
            {
                return this._OrganizationName;
            }
            set
            {
                this._OrganizationName = value;
            }
        }

    
        /// <summary>
        /// There are no comments for OrganizationDesc in the schema.
        /// </summary>
        public virtual string OrganizationDesc
        {
            get
            {
                return this._OrganizationDesc;
            }
            set
            {
                this._OrganizationDesc = value;
            }
        }

    
        /// <summary>
        /// There are no comments for ActiveYear in the schema.
        /// </summary>
        public virtual int ActiveYear
        {
            get
            {
                return this._ActiveYear;
            }
            set
            {
                this._ActiveYear = value;
            }
        }

    
        /// <summary>
        /// There are no comments for ReportStatusFlag in the schema.
        /// </summary>
        public virtual bool ReportStatusFlag
        {
            get
            {
                return this._ReportStatusFlag;
            }
            set
            {
                this._ReportStatusFlag = value;
            }
        }

    
        /// <summary>
        /// There are no comments for FormedDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> FormedDate
        {
            get
            {
                return this._FormedDate;
            }
            set
            {
                this._FormedDate = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DisbandDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DisbandDate
        {
            get
            {
                return this._DisbandDate;
            }
            set
            {
                this._DisbandDate = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateCreated in the schema.
        /// </summary>
        public virtual System.DateTime DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this._DateCreated = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateModified in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this._DateModified = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateDeleted in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateDeleted
        {
            get
            {
                return this._DateDeleted;
            }
            set
            {
                this._DateDeleted = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Comments in the schema.
        /// </summary>
        public virtual string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                this._Comments = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderOrganizationStatusHistories in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderOrganizationStatusHistories
        {
            get
            {
                return this._BeholderOrganizationStatusHistories;
            }
            set
            {
                this._BeholderOrganizationStatusHistories = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderChapters in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderChapters
        {
            get
            {
                return this._BeholderChapters;
            }
            set
            {
                this._BeholderChapters = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderActiveStatus in the schema.
        /// </summary>
        public virtual BeholderActiveStatus BeholderActiveStatus
        {
            get
            {
                return this._BeholderActiveStatus;
            }
            set
            {
                this._BeholderActiveStatus = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderApprovalStatus in the schema.
        /// </summary>
        public virtual BeholderApprovalStatus BeholderApprovalStatus
        {
            get
            {
                return this._BeholderApprovalStatus;
            }
            set
            {
                this._BeholderApprovalStatus = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderConfidentialityType in the schema.
        /// </summary>
        public virtual BeholderConfidentialityType BeholderConfidentialityType
        {
            get
            {
                return this._BeholderConfidentialityType;
            }
            set
            {
                this._BeholderConfidentialityType = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderMovementClass in the schema.
        /// </summary>
        public virtual BeholderMovementClass BeholderMovementClass
        {
            get
            {
                return this._BeholderMovementClass;
            }
            set
            {
                this._BeholderMovementClass = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderOrganizationType in the schema.
        /// </summary>
        public virtual BeholderOrganizationType BeholderOrganizationType
        {
            get
            {
                return this._BeholderOrganizationType;
            }
            set
            {
                this._BeholderOrganizationType = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_CreatedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_CreatedUserId
        {
            get
            {
                return this._SecurityUser_CreatedUserId;
            }
            set
            {
                this._SecurityUser_CreatedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_DeletedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_DeletedUserId
        {
            get
            {
                return this._SecurityUser_DeletedUserId;
            }
            set
            {
                this._SecurityUser_DeletedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_ModifiedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_ModifiedUserId
        {
            get
            {
                return this._SecurityUser_ModifiedUserId;
            }
            set
            {
                this._SecurityUser_ModifiedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAliasOrganizationRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAliasOrganizationRels
        {
            get
            {
                return this._BeholderAliasOrganizationRels;
            }
            set
            {
                this._BeholderAliasOrganizationRels = value;
            }
        }
    }

}
