//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 1/27/2013 7:27:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using splc.infrastructure.Repository;

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace splc.domain
{

    /// <summary>
    /// There are no comments for splc.domain.CommonAddress, splc.domain in the schema.
    /// </summary>
    public partial class CommonAddress : IKeyed<int>
    {

        private int _Id;

        private string _Address1;

        private string _Address2;

        private string _City;

        private string _County;

        private string _Zip5;

        private string _Zip4;

        private System.Nullable<decimal> _Longitude;

        private System.Nullable<decimal> _Latitude;

        private System.DateTime _DateCreated;

        private System.Nullable<System.DateTime> _DateModified;

        private System.Nullable<System.DateTime> _DateDeleted;

        private Iesi.Collections.ISet _BeholderAddressEventRels;

        private Iesi.Collections.ISet _BeholderAddressContactRels;

        private Iesi.Collections.ISet _BeholderAddressSubscriptionsRels;

        private Iesi.Collections.ISet _BeholderAddressCompanyRels;

        private Iesi.Collections.ISet _BeholderAddressVehicleTagRels;

        private CommonState _CommonState;

        private SecurityUser _SecurityUser_CreatedUserId;

        private SecurityUser _SecurityUser_DeletedUserId;

        private SecurityUser _SecurityUser_ModifiedUserId;

        private Iesi.Collections.ISet _CommonAddressPersonRels;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public CommonAddress()
        {
            this._BeholderAddressEventRels = new Iesi.Collections.HashedSet();
            this._BeholderAddressContactRels = new Iesi.Collections.HashedSet();
            this._BeholderAddressSubscriptionsRels = new Iesi.Collections.HashedSet();
            this._BeholderAddressCompanyRels = new Iesi.Collections.HashedSet();
            this._BeholderAddressVehicleTagRels = new Iesi.Collections.HashedSet();
            this._CommonAddressPersonRels = new Iesi.Collections.HashedSet();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Address1 in the schema.
        /// </summary>
        public virtual string Address1
        {
            get
            {
                return this._Address1;
            }
            set
            {
                this._Address1 = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Address2 in the schema.
        /// </summary>
        public virtual string Address2
        {
            get
            {
                return this._Address2;
            }
            set
            {
                this._Address2 = value;
            }
        }

    
        /// <summary>
        /// There are no comments for City in the schema.
        /// </summary>
        public virtual string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this._City = value;
            }
        }

    
        /// <summary>
        /// There are no comments for County in the schema.
        /// </summary>
        public virtual string County
        {
            get
            {
                return this._County;
            }
            set
            {
                this._County = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Zip5 in the schema.
        /// </summary>
        public virtual string Zip5
        {
            get
            {
                return this._Zip5;
            }
            set
            {
                this._Zip5 = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Zip4 in the schema.
        /// </summary>
        public virtual string Zip4
        {
            get
            {
                return this._Zip4;
            }
            set
            {
                this._Zip4 = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Longitude in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Longitude
        {
            get
            {
                return this._Longitude;
            }
            set
            {
                this._Longitude = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Latitude in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Latitude
        {
            get
            {
                return this._Latitude;
            }
            set
            {
                this._Latitude = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateCreated in the schema.
        /// </summary>
        public virtual System.DateTime DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this._DateCreated = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateModified in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this._DateModified = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateDeleted in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateDeleted
        {
            get
            {
                return this._DateDeleted;
            }
            set
            {
                this._DateDeleted = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAddressEventRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAddressEventRels
        {
            get
            {
                return this._BeholderAddressEventRels;
            }
            set
            {
                this._BeholderAddressEventRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAddressContactRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAddressContactRels
        {
            get
            {
                return this._BeholderAddressContactRels;
            }
            set
            {
                this._BeholderAddressContactRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAddressSubscriptionsRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAddressSubscriptionsRels
        {
            get
            {
                return this._BeholderAddressSubscriptionsRels;
            }
            set
            {
                this._BeholderAddressSubscriptionsRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAddressCompanyRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAddressCompanyRels
        {
            get
            {
                return this._BeholderAddressCompanyRels;
            }
            set
            {
                this._BeholderAddressCompanyRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAddressVehicleTagRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAddressVehicleTagRels
        {
            get
            {
                return this._BeholderAddressVehicleTagRels;
            }
            set
            {
                this._BeholderAddressVehicleTagRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonState in the schema.
        /// </summary>
        public virtual CommonState CommonState
        {
            get
            {
                return this._CommonState;
            }
            set
            {
                this._CommonState = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_CreatedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_CreatedUserId
        {
            get
            {
                return this._SecurityUser_CreatedUserId;
            }
            set
            {
                this._SecurityUser_CreatedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_DeletedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_DeletedUserId
        {
            get
            {
                return this._SecurityUser_DeletedUserId;
            }
            set
            {
                this._SecurityUser_DeletedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_ModifiedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_ModifiedUserId
        {
            get
            {
                return this._SecurityUser_ModifiedUserId;
            }
            set
            {
                this._SecurityUser_ModifiedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonAddressPersonRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet CommonAddressPersonRels
        {
            get
            {
                return this._CommonAddressPersonRels;
            }
            set
            {
                this._CommonAddressPersonRels = value;
            }
        }
    }

}
