//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 1/27/2013 7:27:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using splc.infrastructure.Repository;

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace splc.domain
{

    /// <summary>
    /// There are no comments for splc.domain.CommonPrimaryStatus, splc.domain in the schema.
    /// </summary>
    public partial class CommonPrimaryStatus : IKeyed<int>
    {

        private int _Id;

        private string _Name;

        private System.Nullable<int> _SortOrder;

        private System.DateTime _DateCreated;

        private int _CreatedUserId;

        private System.Nullable<System.DateTime> _DateModified;

        private System.Nullable<int> _ModifiedUserId;

        private System.Nullable<System.DateTime> _DateDeleted;

        private System.Nullable<int> _DeletedUserId;

        private Iesi.Collections.ISet _BeholderContactCompanyRels;

        private Iesi.Collections.ISet _BeholderContactChapterRels;

        private Iesi.Collections.ISet _BeholderAddressChapterRels;

        private Iesi.Collections.ISet _BeholderAddressEventRels;

        private Iesi.Collections.ISet _BeholderAddressContactRels;

        private Iesi.Collections.ISet _BeholderAliasPersonRels;

        private Iesi.Collections.ISet _BeholderPersonScreenNames;

        private Iesi.Collections.ISet _BeholderAliasOrganizationRels;

        private Iesi.Collections.ISet _BeholderAliasCompanyRels;

        private Iesi.Collections.ISet _BeholderAliasChapterRels;

        private Iesi.Collections.ISet _BeholderAddressSubscriptionsRels;

        private Iesi.Collections.ISet _BeholderAddressCompanyRels;

        private Iesi.Collections.ISet _BeholderAddressVehicleTagRels;

        private Iesi.Collections.ISet _CommonAddressPersonRels;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public CommonPrimaryStatus()
        {
            this._BeholderContactCompanyRels = new Iesi.Collections.HashedSet();
            this._BeholderContactChapterRels = new Iesi.Collections.HashedSet();
            this._BeholderAddressChapterRels = new Iesi.Collections.HashedSet();
            this._BeholderAddressEventRels = new Iesi.Collections.HashedSet();
            this._BeholderAddressContactRels = new Iesi.Collections.HashedSet();
            this._BeholderAliasPersonRels = new Iesi.Collections.HashedSet();
            this._BeholderPersonScreenNames = new Iesi.Collections.HashedSet();
            this._BeholderAliasOrganizationRels = new Iesi.Collections.HashedSet();
            this._BeholderAliasCompanyRels = new Iesi.Collections.HashedSet();
            this._BeholderAliasChapterRels = new Iesi.Collections.HashedSet();
            this._BeholderAddressSubscriptionsRels = new Iesi.Collections.HashedSet();
            this._BeholderAddressCompanyRels = new Iesi.Collections.HashedSet();
            this._BeholderAddressVehicleTagRels = new Iesi.Collections.HashedSet();
            this._CommonAddressPersonRels = new Iesi.Collections.HashedSet();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SortOrder in the schema.
        /// </summary>
        public virtual System.Nullable<int> SortOrder
        {
            get
            {
                return this._SortOrder;
            }
            set
            {
                this._SortOrder = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateCreated in the schema.
        /// </summary>
        public virtual System.DateTime DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this._DateCreated = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CreatedUserId in the schema.
        /// </summary>
        public virtual int CreatedUserId
        {
            get
            {
                return this._CreatedUserId;
            }
            set
            {
                this._CreatedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateModified in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this._DateModified = value;
            }
        }

    
        /// <summary>
        /// There are no comments for ModifiedUserId in the schema.
        /// </summary>
        public virtual System.Nullable<int> ModifiedUserId
        {
            get
            {
                return this._ModifiedUserId;
            }
            set
            {
                this._ModifiedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateDeleted in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateDeleted
        {
            get
            {
                return this._DateDeleted;
            }
            set
            {
                this._DateDeleted = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DeletedUserId in the schema.
        /// </summary>
        public virtual System.Nullable<int> DeletedUserId
        {
            get
            {
                return this._DeletedUserId;
            }
            set
            {
                this._DeletedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderContactCompanyRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderContactCompanyRels
        {
            get
            {
                return this._BeholderContactCompanyRels;
            }
            set
            {
                this._BeholderContactCompanyRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderContactChapterRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderContactChapterRels
        {
            get
            {
                return this._BeholderContactChapterRels;
            }
            set
            {
                this._BeholderContactChapterRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAddressChapterRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAddressChapterRels
        {
            get
            {
                return this._BeholderAddressChapterRels;
            }
            set
            {
                this._BeholderAddressChapterRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAddressEventRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAddressEventRels
        {
            get
            {
                return this._BeholderAddressEventRels;
            }
            set
            {
                this._BeholderAddressEventRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAddressContactRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAddressContactRels
        {
            get
            {
                return this._BeholderAddressContactRels;
            }
            set
            {
                this._BeholderAddressContactRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAliasPersonRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAliasPersonRels
        {
            get
            {
                return this._BeholderAliasPersonRels;
            }
            set
            {
                this._BeholderAliasPersonRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderPersonScreenNames in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderPersonScreenNames
        {
            get
            {
                return this._BeholderPersonScreenNames;
            }
            set
            {
                this._BeholderPersonScreenNames = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAliasOrganizationRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAliasOrganizationRels
        {
            get
            {
                return this._BeholderAliasOrganizationRels;
            }
            set
            {
                this._BeholderAliasOrganizationRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAliasCompanyRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAliasCompanyRels
        {
            get
            {
                return this._BeholderAliasCompanyRels;
            }
            set
            {
                this._BeholderAliasCompanyRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAliasChapterRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAliasChapterRels
        {
            get
            {
                return this._BeholderAliasChapterRels;
            }
            set
            {
                this._BeholderAliasChapterRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAddressSubscriptionsRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAddressSubscriptionsRels
        {
            get
            {
                return this._BeholderAddressSubscriptionsRels;
            }
            set
            {
                this._BeholderAddressSubscriptionsRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAddressCompanyRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAddressCompanyRels
        {
            get
            {
                return this._BeholderAddressCompanyRels;
            }
            set
            {
                this._BeholderAddressCompanyRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAddressVehicleTagRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAddressVehicleTagRels
        {
            get
            {
                return this._BeholderAddressVehicleTagRels;
            }
            set
            {
                this._BeholderAddressVehicleTagRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonAddressPersonRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet CommonAddressPersonRels
        {
            get
            {
                return this._CommonAddressPersonRels;
            }
            set
            {
                this._CommonAddressPersonRels = value;
            }
        }
    }

}
