//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 1/27/2013 7:27:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using splc.infrastructure.Repository;

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace splc.domain
{

    /// <summary>
    /// There are no comments for splc.domain.BeholderContact, splc.domain in the schema.
    /// </summary>
    public partial class BeholderContact : IKeyed<int>
    {

        private int _Id;

        private System.Nullable<int> _ContactIdOld;

        private string _Profession;

        private string _Comments;

        private System.Nullable<System.DateTime> _DateCreated;

        private System.Nullable<System.DateTime> _DateModified;

        private System.Nullable<System.DateTime> _DateDeleted;

        private BeholderContactType _BeholderContactType;

        private BeholderContactTopic _BeholderContactTopic;

        private Iesi.Collections.ISet _BeholderAddressContactRels;

        private BeholderConfidentialityType _BeholderConfidentialityType;

        private SecurityUser _SecurityUser_CreatedUserId;

        private SecurityUser _SecurityUser_DeletedUserId;

        private SecurityUser _SecurityUser_ModifiedUserId;

        private CommonPerson _CommonPerson;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public BeholderContact()
        {
            this._BeholderAddressContactRels = new Iesi.Collections.HashedSet();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }

    
        /// <summary>
        /// There are no comments for ContactIdOld in the schema.
        /// </summary>
        public virtual System.Nullable<int> ContactIdOld
        {
            get
            {
                return this._ContactIdOld;
            }
            set
            {
                this._ContactIdOld = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Profession in the schema.
        /// </summary>
        public virtual string Profession
        {
            get
            {
                return this._Profession;
            }
            set
            {
                this._Profession = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Comments in the schema.
        /// </summary>
        public virtual string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                this._Comments = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateCreated in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this._DateCreated = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateModified in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this._DateModified = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateDeleted in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateDeleted
        {
            get
            {
                return this._DateDeleted;
            }
            set
            {
                this._DateDeleted = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderContactType in the schema.
        /// </summary>
        public virtual BeholderContactType BeholderContactType
        {
            get
            {
                return this._BeholderContactType;
            }
            set
            {
                this._BeholderContactType = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderContactTopic in the schema.
        /// </summary>
        public virtual BeholderContactTopic BeholderContactTopic
        {
            get
            {
                return this._BeholderContactTopic;
            }
            set
            {
                this._BeholderContactTopic = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAddressContactRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAddressContactRels
        {
            get
            {
                return this._BeholderAddressContactRels;
            }
            set
            {
                this._BeholderAddressContactRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderConfidentialityType in the schema.
        /// </summary>
        public virtual BeholderConfidentialityType BeholderConfidentialityType
        {
            get
            {
                return this._BeholderConfidentialityType;
            }
            set
            {
                this._BeholderConfidentialityType = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_CreatedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_CreatedUserId
        {
            get
            {
                return this._SecurityUser_CreatedUserId;
            }
            set
            {
                this._SecurityUser_CreatedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_DeletedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_DeletedUserId
        {
            get
            {
                return this._SecurityUser_DeletedUserId;
            }
            set
            {
                this._SecurityUser_DeletedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_ModifiedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_ModifiedUserId
        {
            get
            {
                return this._SecurityUser_ModifiedUserId;
            }
            set
            {
                this._SecurityUser_ModifiedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonPerson in the schema.
        /// </summary>
        public virtual CommonPerson CommonPerson
        {
            get
            {
                return this._CommonPerson;
            }
            set
            {
                this._CommonPerson = value;
            }
        }
    }

}
