//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 1/27/2013 7:27:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using splc.infrastructure.Repository;

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace splc.domain
{

    /// <summary>
    /// There are no comments for splc.domain.BeholderCompany, splc.domain in the schema.
    /// </summary>
    public partial class BeholderCompany : IKeyed<int>
    {

        private int _Id;

        private string _CompanyName;

        private string _CompanyDesc;

        private string _BusinessLicenseInfo;

        private System.Nullable<System.DateTime> _OpenDate;

        private System.Nullable<System.DateTime> _CloseDate;

        private System.Nullable<int> _YearsInBusiness;

        private System.DateTime _DateCreated;

        private System.Nullable<System.DateTime> _DateModified;

        private System.Nullable<System.DateTime> _DateDeleted;

        private Iesi.Collections.ISet _BeholderContactCompanyRels;

        private BeholderActiveStatus _BeholderActiveStatus;

        private BeholderBusinessClass _BeholderBusinessClass;

        private BeholderCompanyType _BeholderCompanyType;

        private BeholderConfidentialityType _BeholderConfidentialityType;

        private BeholderMovementClass _BeholderMovementClass;

        private SecurityUser _SecurityUser_CreatedUserId;

        private SecurityUser _SecurityUser_DeletedUserId;

        private SecurityUser _SecurityUser_ModifiedUserId;

        private Iesi.Collections.ISet _BeholderAliasCompanyRels;

        private Iesi.Collections.ISet _BeholderAddressCompanyRels;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public BeholderCompany()
        {
            this._BeholderContactCompanyRels = new Iesi.Collections.HashedSet();
            this._BeholderAliasCompanyRels = new Iesi.Collections.HashedSet();
            this._BeholderAddressCompanyRels = new Iesi.Collections.HashedSet();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CompanyName in the schema.
        /// </summary>
        public virtual string CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                this._CompanyName = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CompanyDesc in the schema.
        /// </summary>
        public virtual string CompanyDesc
        {
            get
            {
                return this._CompanyDesc;
            }
            set
            {
                this._CompanyDesc = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BusinessLicenseInfo in the schema.
        /// </summary>
        public virtual string BusinessLicenseInfo
        {
            get
            {
                return this._BusinessLicenseInfo;
            }
            set
            {
                this._BusinessLicenseInfo = value;
            }
        }

    
        /// <summary>
        /// There are no comments for OpenDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> OpenDate
        {
            get
            {
                return this._OpenDate;
            }
            set
            {
                this._OpenDate = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CloseDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> CloseDate
        {
            get
            {
                return this._CloseDate;
            }
            set
            {
                this._CloseDate = value;
            }
        }

    
        /// <summary>
        /// There are no comments for YearsInBusiness in the schema.
        /// </summary>
        public virtual System.Nullable<int> YearsInBusiness
        {
            get
            {
                return this._YearsInBusiness;
            }
            set
            {
                this._YearsInBusiness = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateCreated in the schema.
        /// </summary>
        public virtual System.DateTime DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this._DateCreated = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateModified in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this._DateModified = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateDeleted in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateDeleted
        {
            get
            {
                return this._DateDeleted;
            }
            set
            {
                this._DateDeleted = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderContactCompanyRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderContactCompanyRels
        {
            get
            {
                return this._BeholderContactCompanyRels;
            }
            set
            {
                this._BeholderContactCompanyRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderActiveStatus in the schema.
        /// </summary>
        public virtual BeholderActiveStatus BeholderActiveStatus
        {
            get
            {
                return this._BeholderActiveStatus;
            }
            set
            {
                this._BeholderActiveStatus = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderBusinessClass in the schema.
        /// </summary>
        public virtual BeholderBusinessClass BeholderBusinessClass
        {
            get
            {
                return this._BeholderBusinessClass;
            }
            set
            {
                this._BeholderBusinessClass = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderCompanyType in the schema.
        /// </summary>
        public virtual BeholderCompanyType BeholderCompanyType
        {
            get
            {
                return this._BeholderCompanyType;
            }
            set
            {
                this._BeholderCompanyType = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderConfidentialityType in the schema.
        /// </summary>
        public virtual BeholderConfidentialityType BeholderConfidentialityType
        {
            get
            {
                return this._BeholderConfidentialityType;
            }
            set
            {
                this._BeholderConfidentialityType = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderMovementClass in the schema.
        /// </summary>
        public virtual BeholderMovementClass BeholderMovementClass
        {
            get
            {
                return this._BeholderMovementClass;
            }
            set
            {
                this._BeholderMovementClass = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_CreatedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_CreatedUserId
        {
            get
            {
                return this._SecurityUser_CreatedUserId;
            }
            set
            {
                this._SecurityUser_CreatedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_DeletedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_DeletedUserId
        {
            get
            {
                return this._SecurityUser_DeletedUserId;
            }
            set
            {
                this._SecurityUser_DeletedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_ModifiedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_ModifiedUserId
        {
            get
            {
                return this._SecurityUser_ModifiedUserId;
            }
            set
            {
                this._SecurityUser_ModifiedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAliasCompanyRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAliasCompanyRels
        {
            get
            {
                return this._BeholderAliasCompanyRels;
            }
            set
            {
                this._BeholderAliasCompanyRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAddressCompanyRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAddressCompanyRels
        {
            get
            {
                return this._BeholderAddressCompanyRels;
            }
            set
            {
                this._BeholderAddressCompanyRels = value;
            }
        }
    }

}
