//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 1/27/2013 7:27:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using splc.infrastructure.Repository;

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace splc.domain
{

    /// <summary>
    /// There are no comments for splc.domain.CommonAlias, splc.domain in the schema.
    /// </summary>
    public partial class CommonAlias : IKeyed<int>
    {

        private int _Id;

        private string _AliasName;

        private System.DateTime _DateCreated;

        private System.Nullable<System.DateTime> _DateModified;

        private System.Nullable<System.DateTime> _DateDeleted;

        private Iesi.Collections.ISet _BeholderAliasPersonRels;

        private Iesi.Collections.ISet _BeholderAliasCompanyRels;

        private Iesi.Collections.ISet _BeholderAliasChapterRels;

        private SecurityUser _SecurityUser_CreatedUserId;

        private SecurityUser _SecurityUser_DeletedUserId;

        private SecurityUser _SecurityUser_ModifiedUserId;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public CommonAlias()
        {
            this._BeholderAliasPersonRels = new Iesi.Collections.HashedSet();
            this._BeholderAliasCompanyRels = new Iesi.Collections.HashedSet();
            this._BeholderAliasChapterRels = new Iesi.Collections.HashedSet();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }

    
        /// <summary>
        /// There are no comments for AliasName in the schema.
        /// </summary>
        public virtual string AliasName
        {
            get
            {
                return this._AliasName;
            }
            set
            {
                this._AliasName = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateCreated in the schema.
        /// </summary>
        public virtual System.DateTime DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this._DateCreated = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateModified in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this._DateModified = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateDeleted in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateDeleted
        {
            get
            {
                return this._DateDeleted;
            }
            set
            {
                this._DateDeleted = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAliasPersonRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAliasPersonRels
        {
            get
            {
                return this._BeholderAliasPersonRels;
            }
            set
            {
                this._BeholderAliasPersonRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAliasCompanyRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAliasCompanyRels
        {
            get
            {
                return this._BeholderAliasCompanyRels;
            }
            set
            {
                this._BeholderAliasCompanyRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAliasChapterRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAliasChapterRels
        {
            get
            {
                return this._BeholderAliasChapterRels;
            }
            set
            {
                this._BeholderAliasChapterRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_CreatedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_CreatedUserId
        {
            get
            {
                return this._SecurityUser_CreatedUserId;
            }
            set
            {
                this._SecurityUser_CreatedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_DeletedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_DeletedUserId
        {
            get
            {
                return this._SecurityUser_DeletedUserId;
            }
            set
            {
                this._SecurityUser_DeletedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_ModifiedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_ModifiedUserId
        {
            get
            {
                return this._SecurityUser_ModifiedUserId;
            }
            set
            {
                this._SecurityUser_ModifiedUserId = value;
            }
        }
    }

}
