//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 1/27/2013 7:27:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using splc.infrastructure.Repository;

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace splc.domain
{

    /// <summary>
    /// There are no comments for splc.domain.BeholderSubscription, splc.domain in the schema.
    /// </summary>
    public partial class BeholderSubscription : IKeyed<int>
    {

        private int _Id;

        private System.Nullable<int> _OrderIdOld;

        private string _PublicationName;

        private System.Nullable<System.DateTime> _RenewalPermissionDate;

        private System.Nullable<System.DateTime> _SubscriptionDate;

        private System.DateTime _DateCreated;

        private System.Nullable<System.DateTime> _DateModified;

        private System.Nullable<System.DateTime> _DateDeleted;

        private BeholderActiveStatus _BeholderActiveStatus;

        private SecurityUser _SecurityUser_CreatedUserId;

        private SecurityUser _SecurityUser_DeletedUserId;

        private SecurityUser _SecurityUser_ModifiedUserId;

        private Iesi.Collections.ISet _BeholderAddressSubscriptionsRels;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public BeholderSubscription()
        {
            this._BeholderAddressSubscriptionsRels = new Iesi.Collections.HashedSet();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }

    
        /// <summary>
        /// There are no comments for OrderIdOld in the schema.
        /// </summary>
        public virtual System.Nullable<int> OrderIdOld
        {
            get
            {
                return this._OrderIdOld;
            }
            set
            {
                this._OrderIdOld = value;
            }
        }

    
        /// <summary>
        /// There are no comments for PublicationName in the schema.
        /// </summary>
        public virtual string PublicationName
        {
            get
            {
                return this._PublicationName;
            }
            set
            {
                this._PublicationName = value;
            }
        }

    
        /// <summary>
        /// There are no comments for RenewalPermissionDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> RenewalPermissionDate
        {
            get
            {
                return this._RenewalPermissionDate;
            }
            set
            {
                this._RenewalPermissionDate = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SubscriptionDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> SubscriptionDate
        {
            get
            {
                return this._SubscriptionDate;
            }
            set
            {
                this._SubscriptionDate = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateCreated in the schema.
        /// </summary>
        public virtual System.DateTime DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this._DateCreated = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateModified in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this._DateModified = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateDeleted in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateDeleted
        {
            get
            {
                return this._DateDeleted;
            }
            set
            {
                this._DateDeleted = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderActiveStatus in the schema.
        /// </summary>
        public virtual BeholderActiveStatus BeholderActiveStatus
        {
            get
            {
                return this._BeholderActiveStatus;
            }
            set
            {
                this._BeholderActiveStatus = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_CreatedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_CreatedUserId
        {
            get
            {
                return this._SecurityUser_CreatedUserId;
            }
            set
            {
                this._SecurityUser_CreatedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_DeletedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_DeletedUserId
        {
            get
            {
                return this._SecurityUser_DeletedUserId;
            }
            set
            {
                this._SecurityUser_DeletedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_ModifiedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_ModifiedUserId
        {
            get
            {
                return this._SecurityUser_ModifiedUserId;
            }
            set
            {
                this._SecurityUser_ModifiedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAddressSubscriptionsRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAddressSubscriptionsRels
        {
            get
            {
                return this._BeholderAddressSubscriptionsRels;
            }
            set
            {
                this._BeholderAddressSubscriptionsRels = value;
            }
        }
    }

}
