//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 1/27/2013 7:27:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using splc.infrastructure.Repository;

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace splc.domain
{

    /// <summary>
    /// There are no comments for splc.domain.CommonContact, splc.domain in the schema.
    /// </summary>
    public partial class CommonContact : IKeyed<int>
    {

        private int _Id;

        private string _Contact;

        private string _Extension;

        private System.DateTime _DateCreated;

        private int _CreatedUserId;

        private System.Nullable<System.DateTime> _DateModified;

        private System.Nullable<int> _ModifiedUserId;

        private System.Nullable<System.DateTime> _DateDeleted;

        private System.Nullable<int> _DeletedUserId;

        private Iesi.Collections.ISet _BeholderContactCompanyRels;

        private Iesi.Collections.ISet _BeholderContactChapterRels;

        private Iesi.Collections.ISet _CommonContactPersonRels;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public CommonContact()
        {
            this._BeholderContactCompanyRels = new Iesi.Collections.HashedSet();
            this._BeholderContactChapterRels = new Iesi.Collections.HashedSet();
            this._CommonContactPersonRels = new Iesi.Collections.HashedSet();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Contact in the schema.
        /// </summary>
        public virtual string Contact
        {
            get
            {
                return this._Contact;
            }
            set
            {
                this._Contact = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Extension in the schema.
        /// </summary>
        public virtual string Extension
        {
            get
            {
                return this._Extension;
            }
            set
            {
                this._Extension = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateCreated in the schema.
        /// </summary>
        public virtual System.DateTime DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this._DateCreated = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CreatedUserId in the schema.
        /// </summary>
        public virtual int CreatedUserId
        {
            get
            {
                return this._CreatedUserId;
            }
            set
            {
                this._CreatedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateModified in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this._DateModified = value;
            }
        }

    
        /// <summary>
        /// There are no comments for ModifiedUserId in the schema.
        /// </summary>
        public virtual System.Nullable<int> ModifiedUserId
        {
            get
            {
                return this._ModifiedUserId;
            }
            set
            {
                this._ModifiedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateDeleted in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateDeleted
        {
            get
            {
                return this._DateDeleted;
            }
            set
            {
                this._DateDeleted = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DeletedUserId in the schema.
        /// </summary>
        public virtual System.Nullable<int> DeletedUserId
        {
            get
            {
                return this._DeletedUserId;
            }
            set
            {
                this._DeletedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderContactCompanyRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderContactCompanyRels
        {
            get
            {
                return this._BeholderContactCompanyRels;
            }
            set
            {
                this._BeholderContactCompanyRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderContactChapterRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderContactChapterRels
        {
            get
            {
                return this._BeholderContactChapterRels;
            }
            set
            {
                this._BeholderContactChapterRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonContactPersonRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet CommonContactPersonRels
        {
            get
            {
                return this._CommonContactPersonRels;
            }
            set
            {
                this._CommonContactPersonRels = value;
            }
        }
    }

}
