//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 1/27/2013 7:27:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using splc.infrastructure.Repository;

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace splc.domain
{

    /// <summary>
    /// There are no comments for splc.domain.BeholderPerson, splc.domain in the schema.
    /// </summary>
    public partial class BeholderPerson : IKeyed<int>
    {

        private int _Id;

        private string _DistinguishableMarks;

        private string _Comments;

        private System.Nullable<System.DateTime> _DateCreated;

        private System.Nullable<System.DateTime> _DateModified;

        private System.Nullable<System.DateTime> _DateDeleted;

        private BeholderMovementClass _BeholderMovementClass;

        private BeholderConfidentialityType _BeholderConfidentialityType;

        private Iesi.Collections.ISet _BeholderChapterPersonRels;

        private Iesi.Collections.ISet _BeholderAliasPersonRels;

        private Iesi.Collections.ISet _BeholderPersonScreenNames;

        private SecurityUser _SecurityUser_CreatedUserId;

        private SecurityUser _SecurityUser_DeletedUserId;

        private SecurityUser _SecurityUser_ModifiedUserId;

        private CommonPerson _CommonPerson;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public BeholderPerson()
        {
            this._BeholderChapterPersonRels = new Iesi.Collections.HashedSet();
            this._BeholderAliasPersonRels = new Iesi.Collections.HashedSet();
            this._BeholderPersonScreenNames = new Iesi.Collections.HashedSet();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DistinguishableMarks in the schema.
        /// </summary>
        public virtual string DistinguishableMarks
        {
            get
            {
                return this._DistinguishableMarks;
            }
            set
            {
                this._DistinguishableMarks = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Comments in the schema.
        /// </summary>
        public virtual string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                this._Comments = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateCreated in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this._DateCreated = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateModified in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this._DateModified = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateDeleted in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateDeleted
        {
            get
            {
                return this._DateDeleted;
            }
            set
            {
                this._DateDeleted = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderMovementClass in the schema.
        /// </summary>
        public virtual BeholderMovementClass BeholderMovementClass
        {
            get
            {
                return this._BeholderMovementClass ?? new BeholderMovementClass();
            }
            set
            {
                this._BeholderMovementClass = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderConfidentialityType in the schema.
        /// </summary>
        public virtual BeholderConfidentialityType BeholderConfidentialityType
        {
            get
            {
                return this._BeholderConfidentialityType ?? new BeholderConfidentialityType();
            }
            set
            {
                this._BeholderConfidentialityType = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderChapterPersonRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderChapterPersonRels
        {
            get
            {
                return this._BeholderChapterPersonRels;
            }
            set
            {
                this._BeholderChapterPersonRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAliasPersonRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAliasPersonRels
        {
            get
            {
                return this._BeholderAliasPersonRels;
            }
            set
            {
                this._BeholderAliasPersonRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderPersonScreenNames in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderPersonScreenNames
        {
            get
            {
                return this._BeholderPersonScreenNames;
            }
            set
            {
                this._BeholderPersonScreenNames = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_CreatedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_CreatedUserId
        {
            get
            {
                return this._SecurityUser_CreatedUserId ?? new SecurityUser();
            }
            set
            {
                this._SecurityUser_CreatedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_DeletedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_DeletedUserId
        {
            get
            {
                return this._SecurityUser_DeletedUserId ?? new SecurityUser();
            }
            set
            {
                this._SecurityUser_DeletedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_ModifiedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_ModifiedUserId
        {
            get
            {
                return this._SecurityUser_ModifiedUserId ?? new SecurityUser();
            }
            set
            {
                this._SecurityUser_ModifiedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonPerson in the schema.
        /// </summary>
        public virtual CommonPerson CommonPerson
        {
            get
            {
                return this._CommonPerson;
            }
            set
            {
                this._CommonPerson = value;
            }
        }
    }

}
