//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 1/27/2013 7:27:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using splc.infrastructure.Repository;

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace splc.domain
{

    /// <summary>
    /// There are no comments for splc.domain.CommonPerson, splc.domain in the schema.
    /// </summary>
    public partial class CommonPerson : IKeyed<int>
    {

        private int _Id;

        private string _SSN;

        private string _FName;

        private string _MName;

        private string _LName;

        private System.Nullable<System.DateTime> _DOB;

        private System.Nullable<bool> _ActualDOBIndicator;

        private string _DriversLicenseNumber;

        private System.Nullable<System.DateTime> _DeceasedDate;

        private System.Nullable<bool> _ActualDeceasedDateIndicator;

        private string _Height;

        private string _Weight;

        private System.DateTime _DateCreated;

        private System.Nullable<System.DateTime> _DateModified;

        private System.Nullable<System.DateTime> _DateDeleted;

        private System.Nullable<int> _OldId;

        private Iesi.Collections.ISet _BeholderContacts;

        private Iesi.Collections.ISet _BeholderPeople;

        private CommonSuffix _CommonSuffix;

        private CommonPrefix _CommonPrefix;

        private CommonEyeColor _CommonEyeColor;

        private CommonGender _CommonGender;

        private CommonHairColor _CommonHairColor;

        private CommonHairPattern _CommonHairPattern;

        private CommonLicenseType _CommonLicenseType;

        private CommonMaritialStatus _CommonMaritialStatus;

        private CommonRace _CommonRace;

        private CommonState _CommonState;

        private SecurityUser _SecurityUser_CreatedUserId;

        private SecurityUser _SecurityUser_DeletedUserId;

        private SecurityUser _SecurityUser_ModifiedUserId;

        private Iesi.Collections.ISet _CommonAddressPersonRels;

        private Iesi.Collections.ISet _CommonContactPersonRels;

        private Iesi.Collections.ISet _SecurityUsers_PersonId;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public CommonPerson()
        {
            this._BeholderContacts = new Iesi.Collections.HashedSet();
            this._BeholderPeople = new Iesi.Collections.HashedSet();
            this._CommonAddressPersonRels = new Iesi.Collections.HashedSet();
            this._CommonContactPersonRels = new Iesi.Collections.HashedSet();
            this._SecurityUsers_PersonId = new Iesi.Collections.HashedSet();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SSN in the schema.
        /// </summary>
        public virtual string SSN
        {
            get
            {
                return this._SSN;
            }
            set
            {
                this._SSN = value;
            }
        }

    
        /// <summary>
        /// There are no comments for FName in the schema.
        /// </summary>
        public virtual string FName
        {
            get
            {
                return this._FName;
            }
            set
            {
                this._FName = value;
            }
        }

    
        /// <summary>
        /// There are no comments for MName in the schema.
        /// </summary>
        public virtual string MName
        {
            get
            {
                return this._MName;
            }
            set
            {
                this._MName = value;
            }
        }

    
        /// <summary>
        /// There are no comments for LName in the schema.
        /// </summary>
        public virtual string LName
        {
            get
            {
                return this._LName;
            }
            set
            {
                this._LName = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DOB in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DOB
        {
            get
            {
                return this._DOB;
            }
            set
            {
                this._DOB = value;
            }
        }

    
        /// <summary>
        /// There are no comments for ActualDOBIndicator in the schema.
        /// </summary>
        public virtual System.Nullable<bool> ActualDOBIndicator
        {
            get
            {
                return this._ActualDOBIndicator;
            }
            set
            {
                this._ActualDOBIndicator = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DriversLicenseNumber in the schema.
        /// </summary>
        public virtual string DriversLicenseNumber
        {
            get
            {
                return this._DriversLicenseNumber;
            }
            set
            {
                this._DriversLicenseNumber = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DeceasedDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DeceasedDate
        {
            get
            {
                return this._DeceasedDate;
            }
            set
            {
                this._DeceasedDate = value;
            }
        }

    
        /// <summary>
        /// There are no comments for ActualDeceasedDateIndicator in the schema.
        /// </summary>
        public virtual System.Nullable<bool> ActualDeceasedDateIndicator
        {
            get
            {
                return this._ActualDeceasedDateIndicator;
            }
            set
            {
                this._ActualDeceasedDateIndicator = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Height in the schema.
        /// </summary>
        public virtual string Height
        {
            get
            {
                return this._Height;
            }
            set
            {
                this._Height = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Weight in the schema.
        /// </summary>
        public virtual string Weight
        {
            get
            {
                return this._Weight;
            }
            set
            {
                this._Weight = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateCreated in the schema.
        /// </summary>
        public virtual System.DateTime DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this._DateCreated = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateModified in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this._DateModified = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateDeleted in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateDeleted
        {
            get
            {
                return this._DateDeleted;
            }
            set
            {
                this._DateDeleted = value;
            }
        }

    
        /// <summary>
        /// There are no comments for OldId in the schema.
        /// </summary>
        public virtual System.Nullable<int> OldId
        {
            get
            {
                return this._OldId;
            }
            set
            {
                this._OldId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderContacts in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderContacts
        {
            get
            {
                return this._BeholderContacts;
            }
            set
            {
                this._BeholderContacts = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderPeople in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderPeople
        {
            get
            {
                return this._BeholderPeople;
            }
            set
            {
                this._BeholderPeople = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonSuffix in the schema.
        /// </summary>
        public virtual CommonSuffix CommonSuffix
        {
            get
            {
                return this._CommonSuffix ?? new CommonSuffix();
            }
            set
            {
                this._CommonSuffix = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonPrefix in the schema.
        /// </summary>
        public virtual CommonPrefix CommonPrefix
        {
            get
            {
                return this._CommonPrefix ?? new CommonPrefix();
            }
            set
            {
                this._CommonPrefix = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonEyeColor in the schema.
        /// </summary>
        public virtual CommonEyeColor CommonEyeColor
        {
            get
            {
                return this._CommonEyeColor ?? new CommonEyeColor();
            }
            set
            {
                this._CommonEyeColor = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonGender in the schema.
        /// </summary>
        public virtual CommonGender CommonGender
        {
            get
            {
                return this._CommonGender ?? new CommonGender();
            }
            set
            {
                this._CommonGender = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonHairColor in the schema.
        /// </summary>
        public virtual CommonHairColor CommonHairColor
        {
            get
            {
                return this._CommonHairColor ?? new CommonHairColor();
            }
            set
            {
                this._CommonHairColor = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonHairPattern in the schema.
        /// </summary>
        public virtual CommonHairPattern CommonHairPattern
        {
            get
            {
                return this._CommonHairPattern ?? new CommonHairPattern();
            }
            set
            {
                this._CommonHairPattern = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonLicenseType in the schema.
        /// </summary>
        public virtual CommonLicenseType CommonLicenseType
        {
            get
            {
                return this._CommonLicenseType ?? new CommonLicenseType();
            }
            set
            {
                this._CommonLicenseType = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonMaritialStatus in the schema.
        /// </summary>
        public virtual CommonMaritialStatus CommonMaritialStatus
        {
            get
            {
                return this._CommonMaritialStatus ?? new CommonMaritialStatus();
            }
            set
            {
                this._CommonMaritialStatus = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonRace in the schema.
        /// </summary>
        public virtual CommonRace CommonRace
        {
            get
            {
                return this._CommonRace ?? new CommonRace();
            }
            set
            {
                this._CommonRace = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonState in the schema.
        /// </summary>
        public virtual CommonState CommonState
        {
            get
            {
                return this._CommonState ?? new CommonState();
            }
            set
            {
                this._CommonState = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_CreatedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_CreatedUserId
        {
            get
            {
                return this._SecurityUser_CreatedUserId ?? new SecurityUser();
            }
            set
            {
                this._SecurityUser_CreatedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_DeletedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_DeletedUserId
        {
            get
            {
                return this._SecurityUser_DeletedUserId ?? new SecurityUser();
            }
            set
            {
                this._SecurityUser_DeletedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_ModifiedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_ModifiedUserId
        {
            get
            {
                return this._SecurityUser_ModifiedUserId ?? new SecurityUser();
            }
            set
            {
                this._SecurityUser_ModifiedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonAddressPersonRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet CommonAddressPersonRels
        {
            get
            {
                return this._CommonAddressPersonRels;
            }
            set
            {
                this._CommonAddressPersonRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonContactPersonRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet CommonContactPersonRels
        {
            get
            {
                return this._CommonContactPersonRels;
            }
            set
            {
                this._CommonContactPersonRels = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUsers_PersonId in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet SecurityUsers_PersonId
        {
            get
            {
                return this._SecurityUsers_PersonId;
            }
            set
            {
                this._SecurityUsers_PersonId = value;
            }
        }
    }

}
