//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 1/27/2013 7:27:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using splc.infrastructure.Repository;

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace splc.domain
{

    /// <summary>
    /// There are no comments for splc.domain.BeholderVehicleTag, splc.domain in the schema.
    /// </summary>
    public partial class BeholderVehicleTag : IKeyed<int>
    {

        private int _Id;

        private string _TagNumber;

        private int _IssueYear;

        private string _Comments;

        private System.DateTime _DateCreated;

        private System.Nullable<System.DateTime> _DateModified;

        private System.Nullable<System.DateTime> _DateDeleted;

        private BeholderVehicle _BeholderVehicle;

        private SecurityUser _SecurityUser_CreatedUserId;

        private SecurityUser _SecurityUser_DeletedUserId;

        private SecurityUser _SecurityUser_ModifiedUserId;

        private CommonTagType _CommonTagType;

        private Iesi.Collections.ISet _BeholderAddressVehicleTagRels;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public BeholderVehicleTag()
        {
            this._BeholderAddressVehicleTagRels = new Iesi.Collections.HashedSet();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }

    
        /// <summary>
        /// There are no comments for TagNumber in the schema.
        /// </summary>
        public virtual string TagNumber
        {
            get
            {
                return this._TagNumber;
            }
            set
            {
                this._TagNumber = value;
            }
        }

    
        /// <summary>
        /// There are no comments for IssueYear in the schema.
        /// </summary>
        public virtual int IssueYear
        {
            get
            {
                return this._IssueYear;
            }
            set
            {
                this._IssueYear = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Comments in the schema.
        /// </summary>
        public virtual string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                this._Comments = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateCreated in the schema.
        /// </summary>
        public virtual System.DateTime DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this._DateCreated = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateModified in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this._DateModified = value;
            }
        }

    
        /// <summary>
        /// There are no comments for DateDeleted in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DateDeleted
        {
            get
            {
                return this._DateDeleted;
            }
            set
            {
                this._DateDeleted = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderVehicle in the schema.
        /// </summary>
        public virtual BeholderVehicle BeholderVehicle
        {
            get
            {
                return this._BeholderVehicle;
            }
            set
            {
                this._BeholderVehicle = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_CreatedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_CreatedUserId
        {
            get
            {
                return this._SecurityUser_CreatedUserId;
            }
            set
            {
                this._SecurityUser_CreatedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_DeletedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_DeletedUserId
        {
            get
            {
                return this._SecurityUser_DeletedUserId;
            }
            set
            {
                this._SecurityUser_DeletedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SecurityUser_ModifiedUserId in the schema.
        /// </summary>
        public virtual SecurityUser SecurityUser_ModifiedUserId
        {
            get
            {
                return this._SecurityUser_ModifiedUserId;
            }
            set
            {
                this._SecurityUser_ModifiedUserId = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CommonTagType in the schema.
        /// </summary>
        public virtual CommonTagType CommonTagType
        {
            get
            {
                return this._CommonTagType;
            }
            set
            {
                this._CommonTagType = value;
            }
        }

    
        /// <summary>
        /// There are no comments for BeholderAddressVehicleTagRels in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet BeholderAddressVehicleTagRels
        {
            get
            {
                return this._BeholderAddressVehicleTagRels;
            }
            set
            {
                this._BeholderAddressVehicleTagRels = value;
            }
        }
    }

}
