//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace splc.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimaryStatus
    {
        public PrimaryStatus()
        {
            this.PersonScreenNames = new HashSet<PersonScreenName>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedUserId { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public Nullable<int> DeletedUserId { get; set; }
    
        public virtual ICollection<PersonScreenName> PersonScreenNames { get; set; }
    }
}
